# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "formtastic_validation"
  s.version = "0.1.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wong Liang Zan"]
  s.date = %q{2010-09-08}
  s.description = %q{A formtastic extension that does client side validation}
  s.email = %q{zan@liangzan.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files        = `git ls-files`.split("\n")
  s.executables  = `git ls-files`.split("\n").select{|f| f =~ /^bin/}
  s.require_path = 'lib'
    
  s.homepage = %q{http://github.com/liangzan/formtastic_validation}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Client side validation with formtastic}
  s.test_files = [
    "spec/formtastic_validation_spec.rb",
     "spec/spec_helper.rb"
  ]
  
  s.add_dependency "validation_reflection", ">= 0.3.8"
  s.add_dependency "formtastic", ">= 1.1.0"
  s.add_dependency "rspec", ">= 1.3.0"
  s.add_dependency "rspec-rails", ">= 1.3.2"
  s.add_dependency "rspec_tag_matchers", ">= 1.0.0"
  s.add_dependency "nokogiri", ">= 1.4.2"
  s.add_dependency "activesupport", ">= 2.3.8"
  s.add_dependency "actionpack", ">= 2.3.8"

end

